# Check out https://docs.codemagic.io/getting-started/building-a-react-native-app/ for more information
# Please review and update values in curly braces

workflows:
    react-native:
        name: React Native App
        environment:
            vars:
                XCODE_WORKSPACE: "React-Native-Woocommerce"
                XCODE_SCHEME: "React-Native-Woocommerce"
            node: latest
        scripts:
            - npm install
            # - echo "sdk.dir=$HOME/programs/android-sdk-macosx" > "$FCI_BUILD_DIR/android/local.properties"
            -  react-native run-android
                build Android
                cd android
                ./gradlew assembleDebug
            
               
        artifacts:
            - android/app/build/outputs/**/*.apk
            # - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            # - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM